### ISSUE TITLE
WebSocket constructor breaks dart2js build on Flutter 3.44 / Dart 3.12

### ISSUE THREAD

**Issue by anilkumar572** [cloudwebrtc/dart-sip-ua#584]
**Describe the bug**
sip_ua 1.1.0 fails to compile for Flutter web (flutter build web) on Flutter 3.44.1 / Dart 3.12.1 with the following error:
`lib/src/transports/websocket_web_impl.dart:26:33:
Error: The argument type 'String' can't be assigned to the parameter type 'JSAny'.
      _socket = WebSocket(_url, 'sip');`

**To Reproduce**
Add sip_ua: ^1.0.1 to pubspec.yaml
Run flutter build web --release
Build fails with dart2js compilation error

**Expected behavior**
flutter build web should compile successfully.

**Root Cause & Fix**
WebSocket from package:web has the signature:
`external factory WebSocket(String url, [JSAny protocols]);`
The protocols argument 'sip' must be JSAny, not a plain String. Since dart:js_interop is already imported in the file, the fix is a one-line change in lib/src/transports/websocket_web_impl.dart line 26:

`// Before
_socket = WebSocket(_url, 'sip');

// After
_socket = WebSocket(_url, 'sip'.toJS);`

**System Infomation()**
Flutter: 3.44.1 (stable)
Dart: 3.12.1
sip_ua: 1.1.0
package:web: 1.1.x
